spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    jdbc-url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: qwerty
    hikari:
      pool-name: HikariPool
      maximum-pool-size: 8
      minimum-idle: 2
      idle-timeout: 150000
      max-lifetime: 300000
      connection-timeout: 5000
      validation-timeout: 2000
      leak-detection-threshold: 5000
      register-mbeans: false
  liquibase:
    url: jdbc:postgresql://localhost:5432/postgres
    user: postgres
    password: qwerty
    change-log: classpath:/liquibase/changelog.yml
    default-schema: dictionary
